theme: jekyll-theme-minimal
title: Xiu Tang
description: <center>Researcher at Zhejiang University. I make database queries faster and more accurate. Write me here: <tangxiu@zju.edu.cn>.<center>

logo: './xiutang.jpg'
show_downloads: false
